logging.level.org.springframework=debug
spring.profiles.active=dev


currency-service.url=http://default.hihi.com
currency-service.user=defaultuserdev
currency-service.key=defaultkeydev

management.endpoints.web.exposure.include= health, metrics

